
# @no-cookie-jar
GET http://localhost:8080/api/studysets/65635676cd44ec3fc70fbcdf HTTP/1.1
Cookie: activ8=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMTAwIiwiaWF0IjoxNzAxMTExODk1LCJleHAiOjE3MDExOTgyOTV9.CgDKLnvEFv2jaAQxe17-6zk_x7KPnwLfoxZ36-oOXdE;
content-type: application/json
###

POST http://localhost:8080/api/studysets HTTP/1.1
Cookie: activ8=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMTAwIiwiaWF0IjoxNzAxMTExODk1LCJleHAiOjE3MDExOTgyOTV9.CgDKLnvEFv2jaAQxe17-6zk_x7KPnwLfoxZ36-oOXdE;
content-type: application/json

{
    "studyFolderId": "65635676cd44ec3fc70fbcdf",
    "title": "test studySetTitle2 v",
    "description": "test studySetDesc2. v"
}
###

PUT http://localhost:8080/api/studysets/6564891808ea0340f75691d3 HTTP/1.1
Cookie: activ8=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMTAwIiwiaWF0IjoxNzAxMTExODk1LCJleHAiOjE3MDExOTgyOTV9.CgDKLnvEFv2jaAQxe17-6zk_x7KPnwLfoxZ36-oOXdE;
content-type: application/json

{
    "studyFolderId": "65635676cd44ec3fc70fbcdf",
    "title": "This Title has been updated 2",
    "description": "This Description has been updated 2"
}

