POST http://localhost:8080/api/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "user100",
    "email": "user100@example.com",
    "password": "apa123"
}
content-type: application/json




HTTP/1.1 200 
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Set-Cookie: activ8=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMTAwIiwiaWF0IjoxNzAxMDAyNzc4LCJleHAiOjE3MDEwODkxNzh9.8ud65wllsuZ2RUHDoW31X1O-hRsW6qQ5NF68kuwo7O4; Path=/api; Max-Age=86400; Expires=Mon, 27 Nov 2023 12:46:18 GMT; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 26 Nov 2023 12:46:18 GMT
Connection: close

{
  "id": "65632f489f3e440150a0bbda",
  "username": "user100",
  "email": "user100@example.com"
}